### ISSUE TITLE
RegisterType improvement

### ISSUE THREAD

**Issue by dretax** [xanathar/moonsharp#101]
Doing: script.Call(luaFactFunction, obj);

Is totally fine. How ever, when the LUA user is working with several Unity/API methods, It causes a conversion error, because the type was not registered. Now Actually I'm able to fix this, but how about registering the type automatically instead of throwing an error?

**Comment by xanathar** [comment]
You can use 

UserData.RegistrationPolicy = InteropRegistrationPolicy.Automatic;

However this quickly leads to problems, sometimes functional problems due to how MoonSharp works but, much more important, security ones - basically you should use it only if you know you are the only one which would write scripts or if your users are totally aware that running scripts can have system-wide side effects.

The point is that using an explicit registration you have total control of what functions can be called from scripts - no dangerous functions in the registered types means no dangerous operations in lua scripts.

If, on the other hand, you enable automatic (implicit) registration, you are on a slippery slope towards insecurity.. for example, say that one method of your objects exposes a FileStream.. suddenly you are able to create files here and there and one evil scripter could realistically write a trojan with that. FileStream is one case, but think also of XmlDocument, XDocument, any other stream, any writer, JSON functions reading/writing files, etc. etc. etc.

There's a third option. If you want you can configure the system so that it doesn't throw an error, and non-registered types are simply passed in userdata but not really usable. For that, simply register System.Object !

(I admit I never tried the last one but in theory it should work).

**Comment by dretax** [comment]
I see. For now I check It in a try/catch and register the missing type. I will decide what to do I guess.
